config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/contribution"
  get "static_pages/credits"
  get "static_pages/history"
  get "static_pages/politicians"
  get "static_pages/malaysian"

  root to: "static_pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def test
    puts "LOL"
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contribution
  end

  def credits
  end

  def history
  end

  def politicians
  end

  def malaysian
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnakMalaysia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('icons/hibiscus.png') %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <%= render("shared/navigation") %>
    <%= yield %>
    <%= render("shared/footer") %>
  </body>
</html>

app/views/shared/_footer.html.erb
<main class="bg-nord-snow-light dark:bg-nord-night-lighter">
  <section class="bg-nord-snow-light dark:bg-nord-night-lighter">
    <div class="p-8 grid grid-cols-1 md:grid-cols-2 max-w-screen-xl mx-auto">
      <div class="flex flex-col pb-4 items-center">
        <div class="text-nord-night-light font-medium dark:text-nord-snow-dark">
          Project by Marcus Heng
        </div>
        <div class="flex mt-6">
          <a class="mx-1" href="https://github.com/marcushwz" target="_blank">
            <svg viewBox="0 0 24 24" class="w-6 fill-current text-nord-night-dark dark:text-nord-snow-dark hover:text-nord-primary dark:hover:text-nord-primary"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"></path></svg>
          </a>
          <a class="mx-1" href="https://twitter.com/weizheheng" target="_blank">
            <svg viewBox="0 0 24 24" class="w-6 fill-current text-nord-night-dark dark:text-nord-snow-dark hover:text-nord-primary dark:hover:text-nord-primary"><path d="M23.954 4.569a10 10 0 0 1-2.825.775 4.958 4.958 0 0 0 2.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 0 0-8.384 4.482C7.691 8.094 4.066 6.13 1.64 3.161a4.822 4.822 0 0 0-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 0 1-2.228-.616v.061a4.923 4.923 0 0 0 3.946 4.827 4.996 4.996 0 0 1-2.212.085 4.937 4.937 0 0 0 4.604 3.417 9.868 9.868 0 0 1-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 0 0 7.557 2.209c9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63a9.936 9.936 0 0 0 2.46-2.548l-.047-.02z"></path></svg>
          </a>
          <a class="mx-1" href="https://www.reddit.com/user/marcusheng" target="_blank">
            <svg viewBox="0 0 24 24" class="w-6 fill-current text-nord-night-dark dark:text-nord-snow-dark hover:text-nord-primary dark:hover:text-nord-primary"><path d="M2.204 14.049c-.06.276-.091.56-.091.847 0 3.443 4.402 6.249 9.814 6.249 5.41 0 9.812-2.804 9.812-6.249 0-.274-.029-.546-.082-.809l-.015-.032a.456.456 0 0 1-.029-.165c-.302-1.175-1.117-2.241-2.296-3.103a.422.422 0 0 1-.126-.07c-.026-.02-.045-.042-.067-.064-1.792-1.234-4.356-2.008-7.196-2.008-2.815 0-5.354.759-7.146 1.971a.397.397 0 0 1-.179.124c-1.206.862-2.042 1.937-2.354 3.123a.454.454 0 0 1-.037.171l-.008.015zm9.773 5.441c-1.794 0-3.057-.389-3.863-1.197a.45.45 0 0 1 0-.632.47.47 0 0 1 .635 0c.63.629 1.685.943 3.228.943 1.542 0 2.591-.3 3.219-.929a.463.463 0 0 1 .629 0 .482.482 0 0 1 0 .645c-.809.808-2.065 1.198-3.862 1.198l.014-.028zm-3.606-7.573c-.914 0-1.677.765-1.677 1.677 0 .91.763 1.65 1.677 1.65s1.651-.74 1.651-1.65c0-.912-.739-1.677-1.651-1.677zm7.233 0c-.914 0-1.678.765-1.678 1.677 0 .91.764 1.65 1.678 1.65s1.651-.74 1.651-1.65c0-.912-.739-1.677-1.651-1.677zm4.548-1.595c1.037.833 1.8 1.821 2.189 2.904a1.818 1.818 0 1 0-2.189-2.902v-.002zM2.711 9.963a1.82 1.82 0 0 0-1.173 3.207c.401-1.079 1.172-2.053 2.213-2.876a1.82 1.82 0 0 0-1.039-.329v-.002zm9.217 12.079c-5.906 0-10.709-3.205-10.709-7.142 0-.275.023-.544.068-.809A2.723 2.723 0 0 1 0 11.777a2.725 2.725 0 0 1 2.725-2.713 2.7 2.7 0 0 1 1.797.682c1.856-1.191 4.357-1.941 7.112-1.992l1.812-5.524.404.095s.016 0 .016.002l4.223.993a2.237 2.237 0 0 1 4.296.874c0 1.232-1.003 2.234-2.231 2.234s-2.23-1.004-2.23-2.23l-3.851-.912-1.467 4.477c2.65.105 5.047.854 6.844 2.021a2.663 2.663 0 0 1 1.833-.719 2.716 2.716 0 0 1 2.718 2.711c0 .987-.54 1.886-1.378 2.365.029.255.059.494.059.749-.015 3.938-4.806 7.143-10.72 7.143l-.034.009zm8.179-19.187a1.339 1.339 0 1 0 0 2.678c.732 0 1.33-.6 1.33-1.334 0-.733-.598-1.332-1.347-1.332l.017-.012z"></path></svg>
          </a>
        </div>
        <div class="flex flex-row mt-4 text-nord-night-light text-sm dark:text-nord-snow-dark items-center">
          Made with 
          <svg viewBox="0 0 24 24" class="w-4 mx-1 fill-current text-nord-red"><path d="M12 21a1 1 0 0 1-.71-.29l-7.77-7.78a5.26 5.26 0 0 1 0-7.4 5.24 5.24 0 0 1 7.4 0L12 6.61l1.08-1.08a5.24 5.24 0 0 1 7.4 0 5.26 5.26 0 0 1 0 7.4l-7.77 7.78A1 1 0 0 1 12 21z"></path></svg>
          in Malaysia
        </div>
      </div>
      <div class="flex flex-col p-4 items-center text-nord-night-light font-medium dark:text-nord-snow-dark">
        <p>References: </p>
        <ul class="list-disc ml-4">
          <li>
            <%= link_to "Want to contribute?", "https://github.com/marcushwz/anak-malaysia", target: :_blank, class: "hover:text-nord-primary" %>
          </li>
          <li>
            <%= link_to "Graphic credits", static_pages_credits_path, target: :_blank, class: "hover:text-nord-primary" %>
          </li>
        </ul>
      </div>
    </div>
  </section>
</main>

app/views/shared/_navigation.html.erb
<header x-data="{ mobileMenuOpen: false }" data-controller="theme" class="flex items-center sticky -top-8 z-50 h-24 w-full bg-nord-snow-light dark:bg-nord-night shadow-sm">
  <div class="sticky flex-1 top-0 h-16 flex px-2 py-4 max-w-screen-xl mx-auto items-center justify-between md:px-6 lg:px-8">
    <div class="p-4 flex">
      <%= link_to image_tag("icons/hibiscus.png"), static_pages_home_path, class: "w-8" %>
      <%= link_to "AnakMalaysia", static_pages_home_path, class: "pl-1 text-2xl font-semibold tracking-wider text-nord-night-light focus:shadow-outline dark:text-nord-snow-dark" %>
    </div>
    <nav class="flex"  @click.away="mobileMenuOpen = false">
      <div class="hidden md:flex md:flex-row">
        <%= link_to "History", static_pages_history_path, class: "nav-item" %>
        <%= link_to "Politicians", static_pages_politicians_path, class: "nav-item" %>
        <%= link_to "Malaysian", static_pages_malaysian_path, class: "nav-item" %>
        <%= link_to "About", static_pages_about_path, class: "nav-item" %>
      </div>
      <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="mobileMenuOpen = !mobileMenuOpen">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!mobileMenuOpen" class="fill-current text-nord-night-light dark:text-nord-snow-dark" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z"></path>
          <path x-show="mobileMenuOpen" class="fill-current text-nord-night-light dark:text-nord-snow-dark" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"></path>
        </svg>
        <div x-show.transition.in="mobileMenuOpen" @click.away="mobileMenuOpen = false" class="absolute right-0 w-full mt-4 origin-top-right rounded-md shadow-lg md:w-48">
          <div class="px-2 py-2 bg-nord-snow-light rounded-md shadow dark:bg-nord-night">
            <%= link_to "History", static_pages_history_path, class: "nav-item-dropdown" %>
            <%= link_to "Politicians", static_pages_politicians_path, class: "nav-item-dropdown" %>
            <%= link_to "Malaysian", static_pages_malaysian_path, class: "nav-item-dropdown" %>
            <%= link_to "About", static_pages_about_path, class: "nav-item-dropdown" %>
          </div>
        </div>
      </button>
      <button data-action="theme#toggle" class="w-8 p-1 m-2 rounded-lg focus:outline-none hover:bg-nord-snow-dark dark:hover:bg-nord-night-light">
        <svg viewBox="-2 -3 28 28">
          <path data-theme-target="moon" 
                class="hidden fill-current text-nord-night-light dark:text-nord-snow-dark" 
                d="M12.3 22h-.1a10.31 10.31 0 0 1-7.34-3.15 10.46 10.46 0 0 1-.26-14 
                   10.13 10.13 0 0 1 4-2.74 1 1 0 0 1 1.06.22 1 1 0 0 1 .24 1 8.4 8.4 0 0 0 1.94 8.81 8.47 8.47 
                   0 0 0 8.83 1.94 1 1 0 0 1 1.27 1.29A10.16 10.16 0 0 1 19.6 19a10.28 10.28 0 0 1-7.3 3z">
          </path>
          <path 
            data-theme-target="sun" 
            class="hidden fill-current text-nord-night-light dark:text-nord-snow-dark" 
            d="M12 6a1 1 0 0 0 1-1V3a1 1 0 0 0-2 0v2a1 1 0 0 0 1 1zm9 5h-2a1 1 0 0 0 0 2h2a1 1 
               0 0 0 0-2zM6 12a1 1 0 0 0-1-1H3a1 1 0 0 0 0 2h2a1 1 0 0 0 1-1zm.22-7a1 1 0 0 0-1.39 1.47l1.44 1.39a1 1 0 0 0 .73.28 1 1 0 0 0 .72-.31 
               1 1 0 0 0 0-1.41zM17 8.14a1 1 0 0 0 .69-.28l1.44-1.39A1 1 0 0 0 17.78 5l-1.44 1.42a1 1 0 0 0 0 1.41 1 1 0 0 0 .66.31zM12 18a1 1 0 0 0-1 
               1v2a1 1 0 0 0 2 0v-2a1 1 0 0 0-1-1zm5.73-1.86a1 1 0 0 0-1.39 1.44L17.78 19a1 1 0 0 0 .69.28 1 1 0 0 0 .72-.3 1 1 0 0 0 0-1.42zm-11.46 
               0l-1.44 1.39a1 1 0 0 0 0 1.42 1 1 0 0 0 .72.3 1 1 0 0 0 .67-.25l1.44-1.39a1 1 0 0 0-1.39-1.44zM12 8a4 4 0 1 0 4 4 4 4 0 0 0-4-4z"
           >
          </path>
        </path>
      </svg>
    </button>
  </nav>
</div>
</header>

app/views/shared/_test.html.erb
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
  <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
    <div class="p-4 flex flex-row items-center justify-between">
      <a href="#" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">Flowtrail UI</a>
      <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
      <%= link_to "Stories", static_pages_home_path, class: " block px-4 py-2 mt-2 text-lg tracking-wider rounded-lg text-nord-3 hover:bg-nord-5 dark:text-nord-6 dark:hover:bg-nord-3" %>
      <%= link_to "Future Plan", static_pages_help_path, class: "block px-4 py-2 mt-2 text-lg tracking-wider rounded-lg text-nord-3 hover:bg-nord-5 dark:text-nord-6 dark:hover:bg-nord-3" %>
      <%= link_to "About", static_pages_home_path, class: "block px-4 py-2 mt-2 text-lg tracking-wider rounded-lg text-nord-3 hover:bg-nord-5 dark:text-nord-6 dark:hover:bg-nord-3" %>
      <div @click.away="open = false" class="relative" x-data="{ open: false }">
        <button @click="open = !open" class="flex flex-row items-center w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:focus:bg-gray-600 dark-mode:hover:bg-gray-600 md:w-auto md:inline md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
          <span>Dropdown</span>
          <svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
          <div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Link #1</a>
            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Link #2</a>
            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Link #3</a>
          </div>
        </div>
      </div>    
    </nav>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="h-screen relative bg-nord-snow-light dark:bg-nord-night-darker">
  <h1>StaticPages#about</h1>
  <p>Find me in app/views/static_pages/about.html.erb</p>
</div>

app/views/static_pages/contribution.html.erb
<div class="h-screen relative bg-nord-snow-light dark:bg-nord-night-darker">
  <h1>StaticPages#contribution</h1>
  <p>Find me in app/views/static_pages/contribution.html.erb (updated)</p>
</div>

app/views/static_pages/credits.html.erb
<main class="h-screen grid grid-cols-1 bg-nord-snow-light dark:bg-nord-night">
  <section class="bg-nord-snow-light dark:bg-nord-night">
    <div class="px-8 pt-16 grid grid-cols-1 max-w-screen-xl mx-auto">
      <div class="flex flex-col items-center text-nord-night-light font-medium dark:text-nord-snow-dark">
        <h1 class="text-3xl font-semibold text-nord-night-light dark:text-nord-snow-dark md:text-4xl lg:text-5xl">
          Graphic Credits
        </h1>
        <ul class="list-disc mt-12">
          <li>
            <%= link_to(
              "Hisbiscus icon",
              "https://www.flaticon.com/free-icon/hibiscus_616447",
              target: :_blank,
              class: "hover:text-nord-primary"
            ) %>
          </li>
          <li>
            <%= link_to(
              "Malaysia flag map", 
              "https://pixabay.com/vectors/borders-country-flag-geography-map-2099214/", 
              target: :_blank,
              class: "hover:text-nord-primary"
            ) %>
          </li>
          <li>
            <%= link_to(
              "Politician speaking", 
              "https://www.vecteezy.com/vector-art/150484-press-release-illustration", 
              target: :_blank, 
              class: "hover:text-nord-primary"
            ) %>
          </li>
          <li>
            <%= link_to(
              "Tunku Abdul Rahman Merdeka Scene", 
              "https://www.leaderonomics.com/articles/personal/merdeka", 
              target: :_blank, 
              class: "hover:text-nord-primary"
            ) %>
          </li>
          <li>
            <%= link_to("Malaysian standing together", 
              "https://www.freepik.com/free-vector/hand-drawn-hari-merdeka-illustration_14960903.htm#page=1&query=merdeka&position=26", 
              target: :_blank,
              class: "hover:text-nord-primary") 
            %>
          </li>
        </ul>
      </div>
    </div>
  </section>
</main>

app/views/static_pages/history.html.erb
<main class="h-screen grid grid-cols-1 bg-nord-snow-light dark:bg-nord-night">
  <section class="bg-nord-snow-light dark:bg-nord-night">
    <div class="px-8 pt-16 grid grid-cols-1 max-w-screen-xl mx-auto">
      <div class="flex flex-col items-center">
        <h1 class="text-3xl font-semibold text-nord-night-light dark:text-nord-snow-dark md:text-4xl lg:text-5xl">
          History Page Coming Soon...
        </h1>
      </div>
    </div>
  </section>
</main>

app/views/static_pages/malaysian.html.erb
<main class="h-screen grid grid-cols-1 bg-nord-snow-light dark:bg-nord-night">
  <section class="bg-nord-snow-light dark:bg-nord-night">
    <div class="px-8 pt-16 grid grid-cols-1 max-w-screen-xl mx-auto">
      <div class="flex flex-col items-center">
        <h1 class="text-3xl font-semibold text-nord-night-light dark:text-nord-snow-dark md:text-4xl lg:text-5xl">
          Malaysian Page Coming Soon...
        </h1>
      </div>
    </div>
  </section>
</main>

app/views/static_pages/politicians.html.erb
<main class="h-screen grid grid-cols-1 bg-nord-snow-light dark:bg-nord-night">
  <section class="bg-nord-snow-light dark:bg-nord-night">
    <div class="px-8 pt-16 grid grid-cols-1 max-w-screen-xl mx-auto">
      <div class="flex flex-col items-center">
        <h1 class="text-3xl font-semibold text-nord-night-light dark:text-nord-snow-dark md:text-4xl lg:text-5xl">
          Politician Page Coming Soon...
        </h1>
      </div>
    </div>
  </section>
</main>